# Generated by Django 4.2.6 on 2023-11-23 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('current_price', models.FloatField()),
                ('market_cap', models.BigIntegerField()),
                ('market_cap_rank', models.PositiveIntegerField()),
                ('fully_diluted_valuation', models.BigIntegerField()),
                ('total_volume', models.BigIntegerField()),
                ('high_24h', models.FloatField()),
                ('low_24h', models.FloatField()),
                ('price_change_24h', models.FloatField()),
                ('price_change_percentage_24h', models.FloatField()),
                ('market_cap_change_24h', models.FloatField()),
                ('market_cap_change_percentage_24h', models.FloatField()),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_supply', models.BigIntegerField()),
                ('max_supply', models.BigIntegerField()),
                ('ath', models.FloatField()),
                ('ath_change_percentage', models.FloatField()),
                ('ath_date', models.DateField()),
                ('atl', models.FloatField()),
                ('atl_change_percentage', models.FloatField()),
                ('atl_date', models.DateField()),
                ('price_change_percentage_24h_in_currency', models.FloatField()),
                ('holdings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('portfolio', models.ManyToManyField(blank=True, related_name='portfolio_coins', to='cryptoapp.coin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, related_name='watchlist_coins', to='cryptoapp.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')])),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoapp.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
