# Generated by Django 4.2.6 on 2023-11-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='watchlist',
            new_name='coin',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='holdings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('coin', models.ManyToManyField(blank=True, related_name='portfolio_coins', to='cryptoapp.coin')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoapp.userprofile')),
            ],
        ),
    ]
