# Generated by Django 4.2.6 on 2023-11-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_coin_holdings_userprofile_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='cryptoapp.coin'),
        ),
    ]
