# Generated by Django 4.2.6 on 2023-11-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_remove_portfolio_coin_portfolio_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_doc',
            field=models.ImageField(blank=True, upload_to='user_document_verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
